<?php

namespace app\controllers;

use Yii;
use yii\db\Query;
use yii\web\Controller;

class LoginController extends Controller
{
    public $enableCsrfValidation = false;

    public function beforeAction($action)
    {
        $data = json_decode(file_get_contents("php://input"),true);
        foreach($data as $key=>$value){
            $_POST[$key]=$value;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionLogin(){

        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');
        $query= new Query();
        $userInfo = $query->select("email")->from('user')->where(['email'=>$username,'password'=>sha1($password)])->one();

        $id = $query->select("userId")->from('user')->where(['email'=>$username,'password'=>sha1($password)])->one();

        echo json_encode($userInfo);

        if (count($userInfo) == 1){
            $token = $username . " | " . uniqid() . uniqid() . uniqid();
            Yii::$app->db->createCommand()
                ->update('user', array('token'=>$token), array('userId'=>$id))
                ->execute();
        }
    }

    public function actionLogout(){

        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');
        $query= new Query();
        $id = $query->select("userId")->from('user')->where(['email'=>$username,'password'=>sha1($password)])->one();

        //$token = $query->select("token")->from('user')->where(['email'=>$username,'password'=>sha1($password), 'userId'=>$id])->one();

        $token = Yii::$app->db->createCommand()
            ->update('user', array('token'=>'LOGOUT'), array('userId'=>$id))
            ->execute();

        echo json_encode($token);
    }
}
