<?php

namespace app\controllers;

use Yii;
use yii\db\Query;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;


class LoginController extends Controller
{
    public $enableCsrfValidation = false;
    public $id = null;

    public function beforeAction($action)
    {
        $data = json_decode(file_get_contents("php://input"),true);
        foreach($data as $key=>$value){
            $_POST[$key]=$value;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionLogin(){

        $model = new LoginForm();
        $model->password=Yii::$app->request->post('password');
        $model->username=Yii::$app->request->post('username');
        if ($model->login()) {
            return "true";
        }
        else{
            return "false";
        }

    }
}
