<?php

namespace app\controllers;

use Yii;
use yii\db\Query;
use yii\web\Controller;
use app\models\LoginForm;


class LoginController extends Controller
{
    public $enableCsrfValidation = false;
    public $id = null;

    public function beforeAction($action)
    {
        $data = json_decode(file_get_contents("php://input"),true);
        foreach($data as $key=>$value){
            $_POST[$key]=$value;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionLogin(){

        $model = new LoginForm();
        $model->password=Yii::$app->request->post('password');
        $model->username=Yii::$app->request->post('username');
        if ($model->login()) {
            return "true";
        }
        else{
            return "false";
        }

    }

    public function actionRestore_password(){

        $email_address = Yii::$app->request->post('restore_password');
        $myemail = $email_address;

        $query= new Query();
        if($userInfo = $query->from('user')->where(['user_email'=>$email_address])->exists())
        {
            $to = $myemail;

            $email_subject = "Restore mail. Please, don't answer this message.";

            $email_body = "You have received a new message. ".

                " Here are the details:\n Name: Kirill  ".

                " Password: qwerty\n";

            $headers = "From: $myemail\n";

            mail($to,$email_subject,$email_body,$headers);

            echo json_encode(1);
        }
        else{
            echo json_encode(0);
        }



    }
}
