<?php

namespace app\controllers;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\bootstrap\Alert;
use app\models\Sign;


class SignController extends Controller
{

    public $enableCsrfValidation = false;

    public function beforeAction($action)
    {
        $data = json_decode(file_get_contents("php://input"),true);
        foreach($data as $key=>$value){
            $_POST[$key]=$value;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionSign(){

        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');
        $passwordConfirm = Yii::$app->request->post('confirmPassword');

        $query= new Query();
        if($userInfo = $query->from('user')->where(['email'=>$username])->exists()
            || $password != $passwordConfirm
            || $username == ""
            || $password ==""
            || $passwordConfirm ==""
            || strlen($password) < 4
            || strlen($username) < 6
        )
        {
            echo json_encode('bad');
        }
        else{
            Yii::$app->db->createCommand()
                ->insert('user',
                    ['email'=>$username,'password'=>sha1($password)])
                ->execute();
            echo json_encode('ok');
        }
    }
}



